<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <style>
    /* General styles */
section {
  margin-top: 4rem;
}

/* Heading styles */
h2[id], h3[id], h4[id], h5[id], h6[id] {
    cursor: pointer;    
    padding: 2rem 0;    
    transition: all 1s, color 0s;
}

/* Before pseudo-element styles */
h2[id]::before,
h3[id]::before,
h4[id]::before,
h5[id]::before,
h6[id]::before {
  display: inline-block;
  width: 2rem;
  height: 2rem;
  border-radius: 1rem;
  margin: 0 1rem;
  content: "#";
  text-align: center;
  line-height: 2rem;
  color: #01BCF1;
  background: #FFD603;
  box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);
  transition: all 0.125s;
}

/* Hover effect on heading */
h2[id]:hover::before,
h3[id]:hover::before,
h4[id]:hover::before,
h5[id]:hover::before,
h6[id]:hover::before {
  color: #FFD603;
  background: #01BCF1;
}
aside.preface {
    background: #ffd6032e;
    padding: 60px;
    border-radius: 30px;
    margin-bottom: 1px;
}
/* Visible section styles */
section.visible {
    padding: 2rem; 
    color: #01BCF1;
    text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.1);
    background: #E6F8FE;
    border-radius: 30px;
}

section.visible h2[id]::before,
section.visible h3[id]::before,
section.visible h4[id]::before,
section.visible h5[id]::before,
section.visible h6[id]::before {
  text-shadow: none;
}

/* Hover effect on visible section */
section.visible h2[id]:hover::before,
section.visible h3[id]:hover::before,
section.visible h4[id]:hover::before,
section.visible h5[id]:hover::before,
section.visible h6[id]:hover::before {
  background: #01BCF1 ;
  color: #FFD603;
}

/* Content container */
.content-container {
  display: flex;
  flex-direction: row-reverse;
}

/* Sidebar styles */
.content-sidebar {
  flex: 0 0 30%;
  padding: 0 1rem;
  border-left: 1px solid rgba(0, 0, 0, 0.1);
  background: #fafafa;
}

/* Navigation styles */
.content-navigation {
  position: sticky;
  top: 0;
  display: flex;
  flex-direction: column;
  width: 100%;
  padding: 2rem 0;
}

.content-navigation a {
    display: block;
    padding: 0.25rem 0;
    text-decoration: none;
    color: #01BCF1;
    font-size: 0.85rem;
}

.content-navigation a.visible {
  color: #FFD603;
}

.content-navigation a.visible ~ a {
  color: #000;
}

.content-navigation .content-navigation-title {
    margin: 10px 0;
    font-size: 1.7rem;
    font-weight: 700;
    text-transform: uppercase;
    color: #FFD603;
}
/* Main content styles */
.content {
  flex: 0 1 70%;
  padding: 4rem;
  font-size: 1.1rem;
  line-height: 1.6;
  overflow-x: scroll;
}
/* Overall container styles */
.container {
    max-width: 100%;
    padding: 0 15px;
    margin: 0 auto;
    box-sizing: border-box;
}

/* Row styles */
.row {
    display: flex;
    flex-wrap: wrap;
    margin: 0 -15px;
}

/* Column styles */
.col-lg-12 {
    flex: 0 0 100%;
    max-width: 100%;
}

/* Preface and content container styles */
.preface, .content-container {
    padding: 20px;
    box-sizing: border-box;
}

/* Strong tag within preface */
.preface strong {
    font-weight: bold;
}

/* Content navigation styles */
.content-navigation-title {
    margin-top: 0;
}

.content-navigation a {
    display: block;
    padding: 10px 0;
}

/* Content styles */
.content {
    padding: 20px;
}

/* Responsive styles for mobile view */
@media screen and (max-width: 767px) {
    /* Adjust padding for preface and content container */
    .preface, .content-container {
        padding: 10px;
    }

    .content{flex: 0 1 100%;}
    /* Hide content navigation on mobile */
    .content-sidebar {
        display: none;
    }

    /* Adjust margin for content navigation title */
    .content-navigation-title {
        margin-top: 20px;
    }

   
    .content-navigation a {
        padding: 5px 0;
    }
}
  </style>
  <body>
    <!--suppress ALL -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <aside class="preface">
                <strong>This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</strong>
                <p>This Privacy Policy (“Privacy Policy”) is published in accordance with: (i) Section 43A of the Information Technology Act, 2000 and (ii) Regulation 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal information) Rules, 2011 (“SPI Rules”) and General Data Protection Regulation. </p>
              
                <p>
                    Please read this Privacy Policy carefully to understand how CRS HosTech Private Limited assigns uses and protects the data you provide. This privacy policy (the “Privacy Policy”) applies to the services provided by CRS HosTech Private Limited on its website <a href="www.blueneckhotels.com">www.blueneckhotels.com</a> and/or mobile application under the brand BlueNeck Hotels (hereinafter collectively referred to as “BlueNeck Hotels”). We are a company registered under the laws of India, having registered office at Plot#1088P, Sector 40, Gurugram, Haryana, India. 122001, India This Privacy Policy applies to all Users (“Users”) of BlueNeck Hotels. For the purpose of the General Data Protection Regulation (“GDPR”), we are the ‘data controller’. Our data protection officer can be contacted at <a href="mailto: dpo@blueneckhotels.com">dpo@blueneckhotels.com</a>.
            
                </p>
                <p>
                    This Privacy Policy covers: (i) the type of data collected from the Users of BlueNeck Hotels including sensitive personal data or data; (ii) the purpose, means and modes of usage of such data; and (iii) how and to whom such data which has been collected will be disclosed.
                </p>
            </aside>
        </div>
    </div>
              <div class="row">
                <div class="col-lg-12">
                    <main class="content-container">
                        <aside class="content-sidebar">
                         <nav class="content-navigation">
                          <header>
                           <h2 class="content-navigation-title">Importants</h2>
                          </header>
                          <a href="#section-Intersection_observer_concepts_and_usage">1. WHAT DATA BLUENECK HOTELS COLLECTS FROM YOU</a>   
                          <a href="#section-Creating_an_intersection_observer">2. HOW BLUENECK HOTELS COLLECTS YOUR DATA</a>   
                          <a href="#section-Intersection_observer_options">3. HOW BLUENECK HOTELS USES YOUR INFORMATION</a>   
                          <a href="#section-Targeting_an_element_to_be_observed">4. HOW TO ACCESS AND CHANGE YOUR PERSONAL DATA</a>   
                          <a href="#section-How_intersection_is_calculated">5. DISCLOSURE OF DATA TO THIRD PARTIES</a>    
                          <a href="#section-Thresholds">6. SAFEGUARDING YOUR PERSONAL DATA</a>   
                          <a href="#section-Intersection_change_callbacks">7. EU DATA Subject Rights</a>   
                          <a href="#section-Interfaces">8. CHANGES TO FABHOTEL'S PRIVACY POLICY</a>   
                          <a href="#section-A_simple_example">9. SPECIAL NOTE REGARDING CHILDREN UNDER 12 YEARS OF AGE</a>  
                          <a href="#section-b_contact_example">10. CONTACT</a>    
                     
                         </nav>
                        </aside>
                        <article class="content" id="wikiArticle">
                    
                         <section id="section-Intersection_observer_concepts_and_usage">
                          <h2 id="Intersection_observer_concepts_and_usage">1. WHAT DATA BLUENECK HOTELS COLLECTS FROM YOU</h2>      
                          <p>BlueNeck Hotels may collect two (2) types of data about you: Personal and Non-Personal.</p><br>
                          <p><b>1.1. Personal Data</b><br>
                            Personal Data refers to data that lets BlueNeck Hotels know the specifics of who you are and which may be used to identify, contact or locate you (e.g. name, age, gender, mailing address, telephone number and e-mail address). BlueNeck Hotels may collect Personal Data when you use the BlueNeck Hotels including, without limitation, setting up account data, making bookings of hotels, filling out surveys, corresponding with BlueNeck Hotels, or otherwise volunteering data about yourself.
                            </p>
                            <p><b>1.2. Non-personal Data</b>
                                Non-Personal Data refers to data that, by itself, does not identify you as a specific individual (e.g. demographic data or website visitations). BlueNeck Hotels may collect Non-Personal Data through any of the methods discussed above as well as automatically through use of industry standard technologies described further below.
                                
                                </p>
                         </section>
                       
                         <section id="section-Creating_an_intersection_observer">
                          <h3 id="Creating_an_intersection_observer">2. HOW BLUENECK HOTELS COLLECTS YOUR DATA</h3>   
                          <p>Subject to clause 7, which provides additional rights to European Residents, The Personal Data practices set forth apply to all BlueNeck Hotels’ customers worldwide.
                        </p>
                        <p><b>2.1. Registration</b><br>
                            Prior to using one or more of the BlueNeck Hotels, BlueNeck Hotels may require certain Personal Data and Non-Personal Data to create an individual account (“Account”) or to enable features or functionality of the BlueNeck Hotels. Failure to provide all required data required by BlueNeck Hotels may prevent access to any or all BlueNeck Hotels, and failure to maintain accurate data may result in suspension or termination of access to any or all BlueNeck Hotels services.
                            </p>
                         <p><b>2.2 Data Collected Through Technology</b><br>
                            While you are able to visit the BlueNeck Hotels and remain anonymous, BlueNeck Hotels or its third party service providers may still collect Non-Personal Data about your use of the BlueNeck Hotels (e.g. your Internet browser, operating system, IP address, connection speed, and the domain name of your Internet service provider). Such data may be gathered by the following methods:
                            </p>
                    
                            <p><b>Cookies-</b><br>
                                Cookies, including local shared objects, are small pieces of data that are stored by your browser on your computer’s hard drive which work by assigning to your system a unique number that has no meaning outside of the BlueNeck Hotels. Cookies do not generally contain any Personal Data. Most web browsers automatically accept cookies, but you can usually configure your browser to prevent this. Not accepting cookies may make certain features of the BlueNeck Hotels unavailable to you.</p>
                    
                            <p><b>Web Beacons-</b><br> Web beacons are small pieces of data that are embedded in web pages and e-mails. BlueNeck Hotels may use these technical methods in HTML e-mails that BlueNeck Hotels sends to Users to determine whether they have opened those e-mails and/or clicked on links in those e-mails. The data from use of these technical methods may be collected in a form that is Personal Data.</p>
                    
                            <p><b>Tracking Content Usage - </b><br> If you use the BlueNeck Hotels Services and you post audio visual materials including, without limitation, text, logos, artwork, graphics, pictures, advertisements, sound and other related intellectual property contained in such materials (collectively, “Content”) to your website or to a third party website, BlueNeck Hotels tracks and captures Non-Personal Data associated with User accounts and the use of Content.</p>
                    
                         </section>
                       
                         <section id="section-Intersection_observer_options">
                          <h4 id="Intersection_observer_options">3. HOW BLUENECK HOTELS USES YOUR INFORMATION</h4>
                       <p>If you are an EU resident, we are required to disclose the legal basis for processing your data under the GDPR.</p>
                       <p>BlueNeck Hotels uses the data that you provide or that we collect to operate, maintain, enhance, and provide all of the features and services found on BlueNeck Hotels as well as to track user-generated content and Users to the extent necessary to comply as a service provider.
                    </p>
                    <p>BlueNeck Hotels may share your registration data, usage data and any other data related to your use of the BlueNeck Hotels site with third parties to the extent set forth in our Terms of Use as updated regularly. We otherwise use all reasonable efforts to protect your data. Additionally, in the event that all resources of the BlueNeck Hotels, that is to say, the entire BlueNeck Hotels, are acquired by another company the personal data required in order to continue to operate BlueNeck Hotels are acquired by the buyer.</p>
                    <p>If you are an EU resident, you can object to profiling and opt-out of receiving any targeted marketing. For more information on this right, please refer the para with the heading “Objection” under Section 7 below.
                    </p>
                    <p><b>3.1. System Administration</b><br>
                        BlueNeck Hotels may use Non-Personal Data for the purposes of system administration, assisting in diagnosing problems with BlueNeck Hotels servers, monitoring BlueNeck Hotels’s system performance and traffic on the BlueNeck Hotels and to gather broad demographic data about BlueNeck Hotels customers.
                        </p>
                        <p><b>3.2 Personalization</b><br>
                            BlueNeck Hotels uses Cookies and IP Addresses to track features such as delivering Content specific to your interests and informing you of new, relevant services or certain third party offerings.
                            </p>
                            <p><b> 3.3 Notices to Registered Users</b><br>
                             If you have registered for an Account, BlueNeck Hotels may use your Personal Data to send e-mails regarding your registration, including confirmation to verify the accuracy of any data you have provided, and instructions on how to post Content. BlueNeck Hotels may also send you e-mails to verify your identity or to notify you if BlueNeck Hotels believes your use of BlueNeck Hotels violates any applicable agreement for the use of the BlueNeck Hotels.
                    
                            </p>
                            <p><b>3.4 Promotional E-mails</b><br>
                                BlueNeck Hotels may use your Personal Data to send you e-mails periodically listing promotions or events relating to the BlueNeck Hotels or from BlueNeck Hotels’ marketing partners or sponsors. You have the choice to opt-out of receiving such promotional e-mails by sending an e-mail to feedback@blueneckhotels.com and/or following the instructions in such correspondence. Once BlueNeck Hotels’ has processed your opt-out request, BlueNeck Hotels will not send you promotional e-mails unless you opt back in to receiving such communications.
                                </p>
                                <p><b>3.5 Contact Data</b><br>
                                    If you contact BlueNeck Hotels by telephone, e-mail or letter, BlueNeck Hotels may keep a record of your contact data and correspondence. If you report a problem with BlueNeck Hotels, BlueNeck Hotels may collect this data in a file specific to you. You may contact BlueNeck Hotels at <a href="mailto: feedback@blueneckhotels.com">feedback@blueneckhotels.com</a> to request the removal of this data from BlueNeck Hotels’ database.</p>
                         </section>
                       
                         <section id="section-Targeting_an_element_to_be_observed">
                          <h4 id="Targeting_an_element_to_be_observed">4. HOW TO ACCESS AND CHANGE YOUR PERSONAL DATA</h4>
                       
                          <p>Upon request, BlueNeck Hotels shall allow Users to update or correct Personal Data previously submitted, but only to the extent such activities will not compromise privacy or security interests. Additionally, upon request, BlueNeck Hotels shall delete Personal Data from the database where such data is stored; however, it may be impossible to entirely delete a User’s entry without some residual data being retained due to the manner in which data backups are maintained. Requests to delete Personal Data shall be submitted to <a href="mailto: feedback@blueneckhotels.com">feedback@blueneckhotels.com</a>.</p>
                          <p>To protect your privacy and security, we take reasonable steps to verify your identity before granting you account access or making corrections to your data. <b>You are responsible for maintaining the secrecy of your unique password and account data at all times.</b></p>
                         </section>
                       
                         <section id="section-How_intersection_is_calculated">
                          <h3 id="How_intersection_is_calculated">5. DISCLOSURE OF DATA TO THIRD PARTIES</h3>
                       <p>BlueNeck Hotels does not sell, trade or rent Personal Data collected through the BlueNeck Hotels to any third party. Notwithstanding the foregoing, BlueNeck Hotels shall: (1) fully cooperate with law enforcement agencies; and (2) may be required to disclose Personal Data upon receipt of a court order, subpoena, or to cooperate with a law enforcement investigation.</p>
                     
                        </section>
                       
                         <section id="section-Thresholds">
                          <h4 id="Thresholds">6. SAFEGUARDING YOUR PERSONAL DATA</h4>
                          <p><b>6.1 Security Measures</b>
                            BlueNeck Hotels takes appropriate security measures to protect against unauthorized access, alteration, disclosure or destruction of Personal Data. These include, but are not limited to, internal reviews of: (a) BlueNeck Hotels’s data collection & encryption; (b) storage and processing practices; (c) electronic security measures; and (d) physical security measures to guard against unauthorized access to systems where BlueNeck Hotels stores Personal Data. All BlueNeck Hotels employees, contractors and agents who access Personal Data are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution or unauthorized use or disclosure of Personal Data.
                           <br>
                           Our Corporate Office is based in Gurgaon, Haryana, India. BlueNeck Hotels infrastructure is primarily based on Cloud and its Core Systems are Software as Service (SaaS) in nature where its Customer Data is stored and accessed. Your data will be accessible to our offices and appointed agents, including agents, sales agents and contact Centre agents, in India and around the world in connection with our performance of the contract with you.
                           <br>
                           This means that Customer Data will be transferred to, and stored at, a destination outside of your country and outside the European Economic Area ("EEA"). If you are an EU resident, where we transfer Customer Data outside the EEA, this is done on the basis that it is necessary for the performance of the contract between you and Fab Hotels.
                        </p>
                        <p><b>6.2 Third Party Links</b>
                            The BlueNeck Hotels may contain links to third parties who may collect Personal Data and Non-Personal Data directly from you. Additionally, BlueNeck Hotels may use third parties to provide components of the BlueNeck Hotels. In either case, such third parties may have separate privacy policies and data collection practices, independent of BlueNeck Hotels. BlueNeck Hotels: (a) has no responsibility or liability for these independent policies or actions; (b) is not responsible for the privacy practices or the content of such websites; and (c) does not make any warranties or representations about the contents, products or services offered on such websites or the security of any data you provide to them.
                            </p>
                         </section>
                       
                         <section id="section-Intersection_change_callbacks">
                          <h3 id="Intersection_change_callbacks">7. EU DATA Subject Rights</h3>   
                          <p>If you are a resident in the EU, you may have certain rights in relation to the data we hold about you, which we detail below. Some of these only apply in certain circumstances where we are holding authority of the data and legally/contractually allowed as per the local laws as set out in more detail below. We also set out how to exercise those rights.
                          </p>
                          These rights include:
                       <ul>
                        <li>The right of access.</li>
                        <li>The right of data portability.</li>
                        <li>The right of rectification.</li>
                        <li>The right of erasure.</li>
                        <li>The right to restrict processing.</li>
                        <li>The right to object.</li>
                    
                       </ul>
                       <p>Please note that we will require you to provide us with proof of identity and address before responding to any requests to exercise your rights. We must respond to a request by you to exercise those rights without undue delay and at least within one month (although this may be extended by a further two months in certain circumstances). To exercise any of your rights, please contact us at dpo@blueneckhotels.com.</p>
                       <p><b>Complaints</b><br>
                        In the event that you wish to make a complaint about how we process your data, please contact us and we will endeavor to deal with your request as soon as possible. This is without prejudice to your right to launch a claim with your data protection authority.
                        </p>
                        <p><b>Access</b><br>
                            You have the right to know whether we process data about you, and if we do, to access data we hold about you and certain information about how we use it and who we share it with. <br>
                            If you require more than one copy of the data we hold about you, we may charge an administration fee. <br>
                            We may not provide you with certain data if providing it would interfere with another’s rights (e.g. where providing the data we hold about you would reveal information about another person) or where another exemption applies.
                            </p>
                            <p><b>Portability</b>
                                You have the right to receive a subset of the data we collect from you in a structured, commonly used and machine-readable format and a right to request that we transfer such data to another party. <br>
                                The relevant subset of data is data that you provide us with your consent or for the purposes of performing our contract with you. <br>
                                If you wish for us to transfer the data to another party, please ensure you detail that party and note that we can only do so where it is legally, contractually and technically feasible. We are not responsible for the security of the data, its transmission or its processing once received by the third party. We also may not provide you with certain data if providing it would interfere with another’s rights (e.g. where providing the data we hold about you would reveal information about another person).
                                </p>
                    
                                <p><b>Correction - </b> <br>
                                    You have the right to correct any data held about you that is inaccurate. We reserve the right to charge a reasonable administrative fee for this service. Please note that whilst we assess whether the data we hold about you is inaccurate or incomplete, you may exercise your right to restrict our processing of the applicable data as described below. <br>
                                    To exercise any of your rights, please contact us at <a href="mailto: dpo@blueneckhotels.com">dpo@blueneckhotels.com.</a></p>
                    
                                    <p><b>Erasure</b> <br>
                    You may request that we erase the data we hold about you in the following circumstances:
                    <ul>
                        <li>you believe that it is no longer necessary for us to hold the data we hold about you;</li>
                        <li>we are processing the data we hold about you on the basis of your consent and you wish to withdraw your consent and there is no other ground under which we can process the data;</li>
                        <li>we are processing the data we hold about you on the basis of our legitimate interest and you object to such processing. Please provide us with detail as to your reasoning so that we can assess whether there is an overriding interest for us to retain such data;</li>
                        <li>you no longer wish us to use the data we hold about you in order to send you promotions, special offers, marketing and lucky draws; or</li>
                        <li>you believe the data we hold about you is being unlawfully processed by us.
                            Also note that you may exercise your right to restrict our processing of the data whilst we consider your request as described below.
                            Please provide as much detail as possible on your reasons for the request to assist us in determining whether you have a valid basis for erasure. However, we may retain the data if there are valid grounds under law for us to do so (e.g., for the defence of legal claims or freedom of expression) but we will let you know if that is the case. Please note that after deleting the data, we may not be able to provide the same level of servicing to you as we will not be aware of your preferences. <br>
                            Where you have requested that we erase data that we have made public and there are grounds for erasure, we will use reasonable steps try to tell others that are displaying the data or providing links to the data to erase the data too. <br>
                            To exercise any of your rights, please contact us at <a href="mailto: 
                            dpo@blueneckhotels.com">dpo@blueneckhotels.com.</a></li>
                    </ul>
                    
                                    </p>
                    
                                    <p>Restriction of Processing to Storage Only
                                        You have a right to require us to stop processing the data we hold about you other than for storage purposes in certain circumstances. Please note, however, that if we stop processing the data, we may use it again if there are valid grounds under data protection law for us to do so (e.g. for the defence of legal claims or for another’s protection). <br>
                                        You may request we stop processing and just store the data we hold about you where:
                                           a. you believe the data is not accurate, for the period it takes for us to verify whether the data is accurate;
                                           b. we wish to erase the data as the processing we are doing is unlawful but you want us to just store it instead;
                                           c. we wish to erase the data as it is no longer necessary for our purposes but you require it to be stored for the establishment, exercise or defence of legal claims; or
                                           d. you have objected to us processing data we hold about you on the basis of our legitimate interest and you wish us to stop processing the data whilst we determine whether there is an overriding interest in us retaining such data.
                                        </p>
                            <p>
                               <b> Objection</b>
                    At any time you have the right to object to our processing of data about you in order to send you promotions, special offers, marketing messages, including where we build profiles for such purposes and we will stop processing the data for that purpose.
                    You also have the right to object to our processing of data about you and we will consider your request in other circumstances as detailed below by contacting  <a href="mailto: dpo@blueneckhotels.com">dpo@blueneckhotels.com</a> <br>
                    <b>referencing:</b> Data Subject Rights.
                    You may object where we are processing the data we hold about you (including where the processing is profiling) on the basis of our legitimate interest and you object to such processing. <br>
                    Please provide us with detail as to your reasoning so that we can assess whether there is a compelling overriding interest in us continuing to process such data or we need to process it in relation to legal claims. Also note that you may exercise your right to request that we stop processing the data whilst we make the assessment on an overriding interest.
                    
                            </p>
                         </section>
                       
                         <section id="section-Interfaces">
                          <h2 id="Interfaces">8. CHANGES TO FABHOTEL'S PRIVACY POLICY</h2>
                       
                         <p>BlueNeck Hotels continually strives to implement new technologies and processes to better protect you, your privacy and your use of the BlueNeck Hotels. As a result, changes to this Privacy Policy may be made by BlueNeck Hotels from time to time. In no event will these changes result in the degradation of any of the security measures designed to protect you from unauthorized disclosure, as such measures are described in this Privacy Policy.</p>
                         </section>
                       
                         <section id="section-A_simple_example">
                          <h2 id="A_simple_example">9. SPECIAL NOTE REGARDING CHILDREN UNDER 12 YEARS OF AGE</h2>
                       
                          <p>Use of the BlueNeck Hotels is not intended for minors under the age of 18 (“Minors”). Minors are not authorized to use the BlueNeck Hotels, even if Minors set up an Account or accept the terms of any agreement for BlueNeck Hotels. Parents or guardians may authorize Minors between the ages of 12 and 17 to use the BlueNeck Hotels, provided they assume all responsibility and legal liability for the conduct of such Minor including, without limitation, monitoring the Minor’s access and use of the BlueNeck Hotels. BlueNeck Hotels does not intentionally collect nor maintain any personally identifiable data from Minors. If you discover your Minor child has submitted his/her data to BlueNeck Hotels, you may request to have such data deleted from BlueNeck Hotels’s database by sending an e-mail request to feedback@blueneckhotels.com together with the e-mail address that was submitted by the Minor. Upon receiving the request, BlueNeck Hotels shall delete such information within 7 business days.</p>
                         </section>
                         <section id="section-b_contact_example">
                            <h2 id="A_simple_example">10. CONTACT</h2>
                            <p>If you have any questions about this Privacy Policy please contact BlueNeck Hotels by sending a letter or e-mail to: <a href="mailto: feedback@blueneckhotels.com">feedback@blueneckhotels.com.</a></p>
                        </section>
                         
                     
                       
                     
                        </article>
                       </main>
                
        </div>
    </div>
</div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script>
    window.addEventListener("load", () => {
 // Retrieve all help sections
 const sections = Array.from(document.querySelectorAll("section[id]"));

 // Once a scrolling event is detected, iterate all elements
 // whose visibility changed and highlight their navigation entry
 const scrollHandler = entries =>
  entries.forEach(entry => {
   const section = entry.target;
   const sectionId = section.id;
   const sectionLink = document.querySelector(`a[href="#${sectionId}"]`);

   if (entry.intersectionRatio > 0) {
    section.classList.add("visible");
    sectionLink.classList.add("visible");
   } else {
    section.classList.remove("visible");
    sectionLink.classList.remove("visible");
   }
  });

 // Creates a new scroll observer
 const observer = new IntersectionObserver(scrollHandler);

 //noinspection JSCheckFunctionSignatures
 sections.forEach(section => observer.observe(section));
});

  </script>
</body>
</html>